CRITICAL - 2024-02-24 08:32:04 --> ErrorException: Undefined variable $imageData
in APPPATH\Controllers\User.php on line 137.
 1 APPPATH\Controllers\User.php(137): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $imageData', 'C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php', 137)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:33:19 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(137): App\Controllers\User->uploadImage(Object(CodeIgniter\HTTP\Files\UploadedFile))
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:40:06 --> ErrorException: require(vendor/autoload.php): Failed to open stream: No such file or directory
in APPPATH\Controllers\User.php on line 4.
 1 APPPATH\Controllers\User.php(4): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(vendor/autoload.php): Failed to open stream: No such file or directory', 'C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php', 4)
 2 APPPATH\Controllers\User.php(4): require()
 3 SYSTEMPATH\Autoloader\Autoloader.php(309): include_once('C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php')
 4 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php')
 5 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\User')
 6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\User')
 7 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\User', true)
 8 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:41:22 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(137): App\Controllers\User->uploadImage(Object(CodeIgniter\HTTP\Files\UploadedFile))
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:43:44 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(137): App\Controllers\User->uploadImage(Object(CodeIgniter\HTTP\Files\UploadedFile))
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:46:21 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:48:52 --> ErrorException: require_once(C:\xampp\htdocs\CI\public\vendor/autoload.php): Failed to open stream: No such file or directory
in APPPATH\Controllers\User.php on line 5.
 1 APPPATH\Controllers\User.php(5): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require_once(C:\\xampp\\htdocs\\CI\\public\\vendor/autoload.php): Failed to open stream: No such file or directory', 'C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php', 5)
 2 APPPATH\Controllers\User.php(5): require_once()
 3 SYSTEMPATH\Autoloader\Autoloader.php(309): include_once('C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php')
 4 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php')
 5 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\User')
 6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\User')
 7 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\User', true)
 8 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:53:09 --> ErrorException: require_once(C:\xampp\htdocs\CI\public\vendor/autoload.php): Failed to open stream: No such file or directory
in APPPATH\Controllers\User.php on line 5.
 1 APPPATH\Controllers\User.php(5): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require_once(C:\\xampp\\htdocs\\CI\\public\\vendor/autoload.php): Failed to open stream: No such file or directory', 'C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php', 5)
 2 APPPATH\Controllers\User.php(5): require_once()
 3 SYSTEMPATH\Autoloader\Autoloader.php(309): include_once('C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php')
 4 SYSTEMPATH\Autoloader\Autoloader.php(288): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\CI\\app\\Controllers\\User.php')
 5 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\User')
 6 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\User')
 7 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\User', true)
 8 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 08:53:32 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 78.
 1 APPPATH\Controllers\User.php(139): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:05:23 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:08:50 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:09:10 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:12:44 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(80): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:15:18 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:18:28 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:22:13 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:26:41 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:28:12 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:29:39 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:54:08 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:57:57 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 09:59:04 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:05:22 --> Error: Call to undefined method Cloudinary\Cloudinary::config()
in APPPATH\Controllers\User.php on line 76.
 1 APPPATH\Controllers\User.php(137): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:08:01 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:08:05 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:09:57 --> Error: Class "Cloudinary" not found
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(138): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:13:27 --> Error: Call to undefined method Cloudinary\Cloudinary::config()
in APPPATH\Controllers\User.php on line 77.
 1 APPPATH\Controllers\User.php(143): App\Controllers\User->uploadImage()
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 10:49:26 --> mysqli_sql_exception: Column 'phone_no' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 10:49:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:49:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:49:26\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:49:26\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:49:26 --> [Caused by] mysqli_sql_exception: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:49:26\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:49:26\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:49:26\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 10:50:20 --> mysqli_sql_exception: Column 'phone_no' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 10:50:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:50:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:50:20\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:50:20\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:50:20 --> [Caused by] mysqli_sql_exception: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:50:20\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:50:20\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:50:20\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 10:51:17 --> mysqli_sql_exception: Column 'phone_no' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 10:51:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:51:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:51:17\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:51:17\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:51:17 --> [Caused by] mysqli_sql_exception: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:51:17\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:51:17\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:51:17\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 10:54:22 --> mysqli_sql_exception: Column 'phone_no' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 10:54:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:54:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:54:22\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:54:22\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:54:22 --> [Caused by] mysqli_sql_exception: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:54:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:54:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:54:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(160): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 10:57:07 --> mysqli_sql_exception: Column 'phone_no' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 10:57:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:57:07 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:57:07\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:57:07\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 10:57:07 --> [Caused by] mysqli_sql_exception: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:57:07\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:57:07\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 10:57:07\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 11:02:04 --> mysqli_sql_exception: Column 'phone_no' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 11:02:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 11:02:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 11:02:04 --> [Caused by] mysqli_sql_exception: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 11:02:20 --> mysqli_sql_exception: Column 'phone_no' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 11:02:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 11:02:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:20\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:20\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 11:02:20 --> [Caused by] mysqli_sql_exception: Column 'phone_no' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:20\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:20\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, \'24-02-24 11:02:20\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(161): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 12:01:05 --> mysqli_sql_exception: Column 'role' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 12:01:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'role' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 12:01:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'role' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', NULL, \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:01:05\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', NULL, \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:01:05\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 12:01:05 --> [Caused by] mysqli_sql_exception: Column 'role' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', NULL, \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:01:05\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', NULL, \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:01:05\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', NULL, \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:01:05\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 12:07:38 --> mysqli_sql_exception: Column 'near_by' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 12:07:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'near_by' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 12:07:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'near_by' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:07:38\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:07:38\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 12:07:38 --> [Caused by] mysqli_sql_exception: Column 'near_by' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:07:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:07:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', NULL, \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:07:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-24 12:09:27 --> mysqli_sql_exception: Column 'accupation' cannot be null in C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\CI\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\CI\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\CI\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\CI\app\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\CI\app\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', Array)
#6 C:\xampp\htdocs\CI\system\CodeIgniter.php(941): App\Controllers\User->create()
#7 C:\xampp\htdocs\CI\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CI\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CI\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-24 12:09:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'accupation' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 2 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 12:09:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'accupation' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', \'ahilasha\', \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:09:27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', \'ahilasha\', \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:09:27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 4 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-24 12:09:27 --> [Caused by] mysqli_sql_exception: Column 'accupation' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', \'ahilasha\', \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:09:27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', \'ahilasha\', \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:09:27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (\'Karan Sharma\', \'6261941674\', \'user\', \'Ujjain\', \'Shri raam colony ankpat marg ujjain\', \'ahilasha\', \'asd\', \'24\', NULL, \'adf\', \'asdf\', \'adf\', \'ad\', \'asdf\', \'24-02-24 12:09:27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`name`, `phone_no`, `role`, `city`, `address`, `near_by`, `nagar`, `age`, `accupation`, `shaka_nagar`, `basti`, `shakha`, `vibhag`, `daitva`, `created_at`) VALUES (:name:, :phone_no:, :role:, :city:, :address:, :near_by:, :nagar:, :age:, :accupation:, :shaka_nagar:, :basti:, :shakha:, :vibhag:, :daitva:, :created_at:)', [...], false)
 5 APPPATH\Models\CommonModel.php(12): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\User.php(162): App\Models\CommonModel->insertValue('users', [...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\User->create()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
